// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
  board: [
    'board/overview',
    {
      type: "category",
      label: "🚀 Test Category",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "🚀 Getting Started",
        description: "Getting Started with Duo",
      },
      items: [
        "board/congratulations",
        "board/create-a-blog-post",
        "board/create-a-page",
        "board/create-a-document",
        "board/deploy-your-site",
        "board/markdown-features",
      ],

    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
